import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

import streamlit as st
import pandas as pd
import json
from src.core.database import SessionLocal
from src.models.hypothesis import Hypothesis
from src.models.governance import GovernanceRecord
from src.models.research_memory import ResearchMemory
from src.models.alpha_registry import AlphaSignal
from sqlalchemy import text

st.set_page_config(page_title="AURUM V2 — Research Terminal", layout="wide")

def get_db():
    return SessionLocal()

def load_hypotheses(db):
    rows = db.query(Hypothesis).order_by(Hypothesis.hypothesis_number).all()
    data = []
    for h in rows:
        gov = db.query(GovernanceRecord).filter_by(hypothesis_id=h.id).first()
        data.append({
            "#": h.hypothesis_number,
            "Title": h.title,
            "Status": h.status.value if h.status else None,
            "Stage": gov.current_stage.value if gov else None,
            "Sharpe": h.sharpe_ratio,
            "Sortino": h.sortino_ratio,
            "Max DD": h.max_drawdown,
            "Ann. Return": h.annualized_return,
            "Win Rate": h.win_rate,
            "Holding (d)": h.expected_holding_days,
            "Has Debate": bool(gov and gov.debate_record),
        })
    return pd.DataFrame(data)

def load_memories(db):
    rows = db.query(ResearchMemory).order_by(ResearchMemory.created_at).all()
    return rows

# ── Sidebar navigation ────────────────────────────────────────────
st.sidebar.title("AURUM V2")
st.sidebar.caption("AI-native quantitative research firm")
page = st.sidebar.radio("Navigate", ["Research Feed", "Hypothesis Detail", "Research Memory", "Memory Lineage", "Alpha Registry", "Research Copilot", "Knowledge Graph", "Portfolio Lab"])
db = get_db()

# ── Page: Research Feed ───────────────────────────────────────────
if page == "Research Feed":
    st.title("Research feed")
    st.caption("Every hypothesis generated by the Research Scientist, with current governance stage and validated performance.")

    df = load_hypotheses(db)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total hypotheses", len(df))
    col2.metric("In paper trading", (df["Stage"] == "paper_trading").sum())
    col3.metric("Debated", df["Has Debate"].sum())
    col4.metric("Avg Sharpe (validated)", round(df["Sharpe"].dropna().mean(), 2) if df["Sharpe"].notna().any() else "—")

    st.divider()

    display_df = df.drop(columns=["Has Debate"]).copy()
    for col in ["Sharpe", "Sortino", "Max DD", "Ann. Return", "Win Rate"]:
        display_df[col] = display_df[col].apply(lambda x: f"{x:.3f}" if pd.notna(x) else "—")

    st.dataframe(display_df, use_container_width=True, hide_index=True)

    st.divider()
    st.markdown("### Pending actions")
    st.caption("Hypotheses waiting for a governance decision.")

    pending_stages = ["idea", "experiment", "statistical_review", "risk_review", "committee"]
    pending = df[df["Stage"].isin(pending_stages) & (df["Status"] != "failed")]

    if pending.empty:
        st.info("Nothing pending — all active hypotheses are either in paper trading, production, or retired.")
    else:
        for _, row in pending.iterrows():
            with st.container(border=True):
                c1, c2, c3 = st.columns([3, 1, 1])
                c1.markdown(f"**#{row['#']} — {row['Title']}**")
                c2.markdown(f"`{row['Stage']}`")
                c3.markdown(f"Sharpe: {row['Sharpe']}")

# ── Page: Hypothesis Detail ───────────────────────────────────────
elif page == "Hypothesis Detail":
    st.title("Hypothesis detail")

    df = load_hypotheses(db)
    hyp_number = st.selectbox("Select hypothesis", df["#"].tolist())

    hyp = db.query(Hypothesis).filter_by(hypothesis_number=hyp_number).first()
    gov = db.query(GovernanceRecord).filter_by(hypothesis_id=hyp.id).first()

    st.subheader(f"#{hyp.hypothesis_number} — {hyp.title}")
    
    # Show persistent action feedback across reruns
    action_key = f"last_action_{hyp.hypothesis_number}"
    if action_key in st.session_state:
        msg = st.session_state[action_key]
        if msg.startswith("✅"):
            st.success(msg)
        else:
            st.error(msg)
        del st.session_state[action_key]
    
    st.write(hyp.thesis)

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Sharpe", f"{hyp.sharpe_ratio:.3f}" if hyp.sharpe_ratio else "—")
    c2.metric("Sortino", f"{hyp.sortino_ratio:.3f}" if hyp.sortino_ratio else "—")
    c3.metric("Max DD", f"{hyp.max_drawdown:.1%}" if hyp.max_drawdown else "—")
    c4.metric("Ann. Return", f"{hyp.annualized_return:.1%}" if hyp.annualized_return else "—")
    c5.metric("Win Rate", f"{hyp.win_rate:.1%}" if hyp.win_rate else "—")

    st.divider()

    tab1, tab2, tab3, tab4 = st.tabs(["Signal components", "Governance timeline", "Committee debate", "Raw JSON"])

    with tab1:
        st.json(hyp.signal_components)
        st.caption(f"Conditions: {json.dumps(hyp.conditions)}")
        st.caption(f"Universe: {hyp.universe} | Holding period: {hyp.expected_holding_days} days")

    with tab2:
        if gov and gov.stage_history:
            for entry in gov.stage_history:
                with st.container(border=True):
                    st.markdown(f"**{entry.get('to_stage', 'unknown')}** — {entry.get('timestamp', '')[:19]}")
                    st.caption(entry.get("notes", ""))
        else:
            st.info("No governance history available.")

        st.divider()
        st.markdown("### Governance actions")

        from src.agents.governance_actions import get_allowed_actions, advance_stage, retire_hypothesis
        from src.models.governance import GovernanceStage

        # Re-fetch gov after any potential rerun to get fresh stage
        gov = db.query(GovernanceRecord).filter_by(hypothesis_id=hyp.id).first()
        actions = get_allowed_actions(hyp, gov)

        if not actions:
            st.info("No actions available from current stage.")
        else:
            notes_key = f"notes_{hyp.hypothesis_number}"
            notes_input = st.text_input(
                "Notes (optional)", key=notes_key,
                placeholder="Reason for this transition..."
            )

            # Handle pending action from previous render cycle
            pending_key = f"pending_action_{hyp.hypothesis_number}"
            if pending_key in st.session_state:
                pending = st.session_state.pop(pending_key)
                target = GovernanceStage(pending["target"])
                notes = pending["notes"]

                if target == GovernanceStage.RETIRED:
                    if not notes:
                        st.error("Retirement reason is required.")
                    else:
                        ok, msg = retire_hypothesis(db, hyp, notes)
                        if ok:
                            st.success(f"✅ {msg}")
                            st.rerun()
                        else:
                            st.error(f"❌ {msg}")
                else:
                    ok, msg = advance_stage(db, hyp, target, notes)
                    if ok:
                        st.success(f"✅ {msg}")
                        st.rerun()
                    else:
                        st.error(f"❌ {msg}")

            # Render action buttons
            for action in actions:
                col_btn, col_reason = st.columns([1, 3])
                btn_key = f"btn_{hyp.hypothesis_number}_{action['target_stage'].value}"

                with col_btn:
                    if action["target_stage"] == GovernanceStage.RETIRED:
                        clicked = st.button(
                            f"🗄️ {action['label']}", key=btn_key,
                            disabled=not action["enabled"], type="secondary"
                        )
                    else:
                        clicked = st.button(
                            f"→ {action['label']}", key=btn_key,
                            disabled=not action["enabled"], type="primary"
                        )

                with col_reason:
                    if not action["enabled"]:
                        st.caption(f"⛔ {action['blocked_reason']}")
                    else:
                        st.caption("✅ Prerequisites met")

                if clicked:
                    st.session_state[pending_key] = {
                        "target": action["target_stage"].value,
                        "notes": notes_input
                    }
                    st.rerun()

    with tab3:
        if gov and gov.debate_record:
            d = gov.debate_record
            colA, colB = st.columns(2)

            with colA:
                st.markdown("### 🐂 Bull case")
                for p in d["bull"]["thesis_points"]:
                    st.markdown(f"- {p}")
                st.success(f"**Strongest argument:** {d['bull']['strongest_argument']}")
                st.caption(f"Confidence: {d['bull']['confidence']}")

            with colB:
                st.markdown("### 🐻 Bear case")
                for p in d["bear"]["rebuttal_points"]:
                    st.markdown(f"- {p}")
                st.error(f"**Strongest objection:** {d['bear']['strongest_objection']}")
                st.caption(f"Confidence: {d['bear']['confidence']}")

            st.divider()
            st.markdown("### ⚖️ Risk assessment")
            for f in d["risk"]["risk_flags"]:
                st.markdown(f"- {f}")
            r1, r2, r3 = st.columns(3)
            r1.metric("Concentration risk", d["risk"]["concentration_risk"])
            r2.metric("Overall rating", d["risk"]["overall_risk_rating"])
            r3.metric("Position limit", d["risk"]["recommended_position_limit"][:30])

            st.divider()
            st.markdown("### 🏛️ Committee decision")
            j = d["judge"]
            decision_color = {"approve_paper_trading": "success", "reject": "error", "request_revision": "warning"}
            getattr(st, decision_color.get(j["decision"], "info"))(f"**{j['decision'].upper()}**")
            st.write(j["justification"])
            st.caption(f"Addressed bear objection: {j['addressed_bear_objection']}")
            if j.get("conditions_for_approval"):
                st.markdown("**Conditions:**")
                for c in j["conditions_for_approval"]:
                    st.markdown(f"- {c}")
        else:
            st.info("This hypothesis has not been through committee debate yet.")

    with tab4:
        st.json({
            "hypothesis": hyp.signal_components,
            "governance_stage": gov.current_stage.value if gov else None,
            "committee_decision": gov.committee_decision if gov else None,
        })

# ── Page: Research Memory ─────────────────────────────────────────
elif page == "Research Memory":
    st.title("Research memory")
    st.caption("Lessons extracted from failed or flawed research, consulted automatically before new hypothesis generation.")

    memories = load_memories(db)

    if not memories:
        st.info("No research memories yet.")
    else:
        st.metric("Total memories", len(memories))
        st.divider()

        for m in memories:
            with st.container(border=True):
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.markdown(f"**{m.failure_mode}**")
                    st.caption(f"From Hypothesis #{m.source_hypothesis_number} · {m.created_by}")
                with col2:
                    st.caption(f"Affects: {', '.join(m.affected_signal_types)}")

                st.write(m.lesson)

                with st.expander("Structured constraint"):
                    st.json(m.structured_constraint)

# ── Page: Memory Lineage ──────────────────────────────────────────
elif page == "Memory Lineage":
    st.title("Memory lineage")
    st.caption("The self-correcting research loop: a debate finds a flaw, a memory captures it, a future hypothesis adapts to it.")

    memories = load_memories(db)
    hyp_lookup = {h.hypothesis_number: h for h in db.query(Hypothesis).all()}

    if not memories:
        st.info("No memories yet.")
    else:
        for m in memories:
            source_hyp = hyp_lookup.get(m.source_hypothesis_number)
            influenced = m.influenced_hypothesis_numbers or []

            with st.container(border=True):
                col1, col2, col3 = st.columns([1, 1, 1])

                with col1:
                    st.markdown("**Source hypothesis**")
                    if source_hyp:
                        st.markdown(f"#{source_hyp.hypothesis_number} — {source_hyp.title}")
                        st.caption(f"Sharpe: {source_hyp.sharpe_ratio} · Max DD: {source_hyp.max_drawdown}")
                    else:
                        st.caption("Unknown source")

                with col2:
                    st.markdown("**→ Memory extracted →**")
                    st.markdown(f"`{m.failure_mode}`")
                    st.caption(m.lesson[:140] + "..." if len(m.lesson) > 140 else m.lesson)

                with col3:
                    st.markdown("**→ Influenced**")
                    if influenced:
                        for hyp_num in influenced:
                            target_hyp = hyp_lookup.get(hyp_num)
                            if target_hyp:
                                st.markdown(f"#{target_hyp.hypothesis_number} — {target_hyp.title}")
                                st.caption(f"Sharpe: {target_hyp.sharpe_ratio} · Max DD: {target_hyp.max_drawdown}")
                    else:
                        st.caption("Not yet applied to a new hypothesis")

        st.divider()
        st.markdown("### Full lineage chain")

        chain_md = """
H3 (no stat review, VIX gate flaw)
H4 (VIX gate flaw, selection bias)
        |
        v
   Memory: timing_mismatch
   Memory: selection_bias
        |
        v
H7 (10-day hold, fixed VIX=18 circuit breaker)
        |
        v
   Backtest reveals: 69.5% trigger rate, Sharpe 1.14 -> 0.31 with breaker on
        |
        v
   Memory: circuit_breaker_overcalibration
        |
        v
H8 (percentile-based dynamic threshold, 88th percentile VIX)
        |
        v
   Debate catches: circular calibration, no out-of-sample validation yet
        |
        v
   Paper trading mandated to validate before live deployment
"""
        st.code(chain_md, language=None)

        st.markdown("""
**The pattern**: every hypothesis after #4 exists because a debate or backtest found a specific,
named flaw in its predecessor. The system is not just generating ideas — it is generating ideas
that respond to its own documented failures, with the response itself then subjected to fresh
scrutiny by the committee.
""")

# ── Page: Alpha Registry ──────────────────────────────────────────
elif page == "Alpha Registry":
    st.title("Alpha registry")
    st.caption("Hypotheses that survived backtest, statistical validation, and committee debate — the system's actual research output.")

    alphas = db.query(AlphaSignal).order_by(AlphaSignal.registered_at).all()
    hyp_lookup = {h.id: h for h in db.query(Hypothesis).all()}

    if not alphas:
        st.info("No alphas registered yet.")
    else:
        c1, c2, c3 = st.columns(3)
        c1.metric("Registered alphas", len(alphas))
        c2.metric("Avg Sharpe", round(sum(a.sharpe_ratio for a in alphas) / len(alphas), 3))
        c3.metric("Active", sum(1 for a in alphas if a.is_active))

        st.divider()

        for a in alphas:
            hyp = hyp_lookup.get(a.hypothesis_id)
            with st.container(border=True):
                col1, col2 = st.columns([2, 1])

                with col1:
                    st.markdown(f"### {a.signal_name}")
                    if hyp:
                        st.caption(f"From Hypothesis #{hyp.hypothesis_number} · Universe: {a.universe} · "
                                   f"Registered {a.registered_at.strftime('%Y-%m-%d')}")

                with col2:
                    status = "🟢 Active" if a.is_active else "⚪ Inactive"
                    st.markdown(f"**{status}**")
                    if a.decay_flag:
                        st.warning("Decay flagged")
                    if a.retirement_recommended:
                        st.error("Retirement recommended")

                m1, m2, m3, m4, m5 = st.columns(5)
                m1.metric("Sharpe", f"{a.sharpe_ratio:.3f}")
                m2.metric("Sortino", f"{a.sortino_ratio:.3f}")
                m3.metric("Calmar", f"{a.calmar_ratio:.3f}")
                m4.metric("Max DD", f"{a.max_drawdown:.1%}")
                m5.metric("Win Rate", f"{a.win_rate:.1%}")

                if a.paper_trading_sharpe is not None:
                    st.caption(f"Paper trading Sharpe: {a.paper_trading_sharpe} "
                               f"(vs. backtest {a.sharpe_ratio})")

                with st.expander("Signal construction logic"):
                    st.code(a.signal_code, language="python")

                with st.expander("Features used"):
                    st.write(", ".join(a.features_used))

                # Latest learning report for this alpha
                latest = db.execute(text(
                    "SELECT paper_sharpe, paper_max_drawdown, paper_win_rate, "
                    "sharpe_degradation, vix_max_observed, vix_breach_occurred, "
                    "circuit_breaker_triggers, recommended_action, evaluated_at "
                    "FROM learning_reports WHERE hypothesis_id = :hid "
                    "ORDER BY evaluated_at DESC LIMIT 1"
                ), {"hid": str(a.hypothesis_id)}).fetchone()

                if latest:
                    with st.expander("Latest learning report"):
                        lr1, lr2, lr3 = st.columns(3)
                        lr1.metric("Paper Sharpe", f"{latest.paper_sharpe:.3f}",
                                   delta=f"{(latest.paper_sharpe - a.sharpe_ratio):.3f} vs backtest")
                        lr2.metric("Paper Max DD", f"{latest.paper_max_drawdown:.1%}")
                        lr3.metric("Recommendation", latest.recommended_action)
                        st.caption(f"Evaluated: {str(latest.evaluated_at)[:19]} | "
                                   f"VIX max: {latest.vix_max_observed} "
                                   f"({'breach' if latest.vix_breach_occurred else 'no breach'}) | "
                                   f"Circuit breaker fired: {latest.circuit_breaker_triggers}x")

# ── Page: Research Copilot ────────────────────────────────────────
elif page == "Research Copilot":
    st.title("Research copilot")
    st.caption("Ask anything about the hypothesis corpus, debate findings, research memories, or alpha registry.")

    from src.agents.research_copilot import query_copilot

    # Example questions
    examples = [
        "Which hypotheses failed because of regime conditioning?",
        "What did the Bear Agent find wrong with H#7?",
        "What lessons have we learned about VIX circuit-breakers?",
        "Which alphas are active and what are their paper trading results?",
        "What should we test next based on what we know?",
        "Which hypotheses have been through the full governance pipeline?",
    ]

    st.markdown("**Example questions** — click to run instantly:")
    cols = st.columns(3)
    for i, ex in enumerate(examples):
        if cols[i % 3].button(ex, key=f"ex_{i}", use_container_width=True):
            with st.spinner("Searching research corpus..."):
                answer = query_copilot(db, ex)
            st.session_state["copilot_answer"] = answer
            st.session_state["copilot_last_question"] = ex
            st.rerun()

    st.divider()

    question = st.text_input(
        "Or ask your own question",
        placeholder="e.g. Which strategies survived the VIX spike?",
        key="copilot_input"
    )

    if st.button("Ask", type="primary", key="copilot_ask") and question:
        with st.spinner("Searching research corpus..."):
            answer = query_copilot(db, question)
        st.session_state["copilot_answer"] = answer
        st.session_state["copilot_last_question"] = question

    if "copilot_answer" in st.session_state:
        st.divider()
        if "copilot_last_question" in st.session_state:
            st.caption(f"Q: {st.session_state['copilot_last_question']}")
        st.markdown("### Answer")
        st.markdown(st.session_state["copilot_answer"])
        if st.button("Clear", key="copilot_clear"):
            del st.session_state["copilot_answer"]
            del st.session_state["copilot_last_question"]

# ── Page: Knowledge Graph ─────────────────────────────────────────
elif page == "Knowledge Graph":
    st.title("Knowledge graph")
    st.caption("Entity relationships, sector peers, ETF exposure, and macro sensitivities — the semantic layer over market data.")

    from src.data.relational_knowledge_store import get_knowledge_store, ENTITY_DATA, ETF_CONSTITUENCIES
    import pandas as pd

    ks = get_knowledge_store()

    tab_sector, tab_etf, tab_entity, tab_crowding = st.tabs([
        "Sector map", "ETF constituencies", "Entity lookup", "Crowding analysis"
    ])

    with tab_sector:
        st.markdown("### Sector distribution across universe")
        sector_data = {}
        for ticker, data in ENTITY_DATA.items():
            sector = data[1]
            sector_data.setdefault(sector, []).append(ticker)

        for sector, tickers in sorted(sector_data.items(), key=lambda x: -len(x[1])):
            with st.container(border=True):
                c1, c2 = st.columns([1, 4])
                c1.metric(sector.split(" ")[-1], len(tickers))
                c2.write(", ".join(tickers))

    with tab_etf:
        st.markdown("### ETF constituency map")
        etf_rows = []
        for etf, tickers in ETF_CONSTITUENCIES.items():
            etf_rows.append({"ETF": etf, "Holdings": len(tickers), "Tickers": ", ".join(tickers[:8]) + ("..." if len(tickers) > 8 else "")})
        st.dataframe(pd.DataFrame(etf_rows), use_container_width=True, hide_index=True)

    with tab_entity:
        st.markdown("### Entity detail")
        ticker = st.selectbox("Select ticker", sorted(ENTITY_DATA.keys()))
        entity = ks.get_entity(ticker)
        if entity:
            c1, c2, c3 = st.columns(3)
            c1.metric("Sector", entity.sector.split(" ")[-1])
            c2.metric("Industry", entity.industry[:20])
            c3.metric("Cap tier", entity.market_cap_tier)

            st.markdown("**ETF memberships:**")
            etfs = ks.get_etf_exposure(ticker)
            if etfs:
                st.write(", ".join(e["etf"] for e in etfs))
            else:
                st.write("None in our tracked ETFs")

            st.markdown("**Macro sensitivities:**")
            macros = ks.get_macro_sensitivities(ticker)
            for m in macros:
                st.markdown(f"- `{m}`")

            st.markdown("**Sector peers:**")
            peers = ks.get_peers(ticker)
            st.write(", ".join(p.ticker for p in peers))

    with tab_crowding:
        st.markdown("### Portfolio crowding analysis")
        st.caption("Select tickers to see ETF overlap and sector concentration risk.")

        selected = st.multiselect(
            "Select tickers",
            sorted(ENTITY_DATA.keys()),
            default=["NVDA", "AMD", "META", "MSFT", "AAPL", "GOOGL", "AMZN"]
        )

        if selected:
            c1, c2 = st.columns(2)

            with c1:
                st.markdown("**Sector concentration:**")
                concentration = ks.get_sector_concentration(selected)
                for sector, info in concentration.items():
                    flag = "⚠️" if info["concentration_flag"] else "✅"
                    st.markdown(f"{flag} **{sector}**: {info['count']} tickers ({info['pct']*100:.0f}%)")

            with c2:
                st.markdown("**ETF crowding:**")
                crowding = ks.get_common_etf_exposure(selected)
                if crowding:
                    for etf, info in sorted(crowding.items(), key=lambda x: -x[1]["overlap_count"])[:8]:
                        risk_color = "🔴" if info["concentration_risk"] == "high" else "🟡" if info["concentration_risk"] == "medium" else "🟢"
                        st.markdown(f"{risk_color} **{etf}**: {info['overlap_count']}/{len(selected)} names")
                else:
                    st.info("No common ETF exposure found.")

# ── Page: Portfolio Lab ───────────────────────────────────────────
elif page == "Portfolio Lab":
    st.title("Portfolio laboratory")
    st.caption("Stress-test registered alphas against macro and market shock scenarios.")

    from src.agents.portfolio_lab import SCENARIOS, estimate_alpha_scenario_impact, explain_scenario_impact
    from src.models.alpha_registry import AlphaSignal

    alphas = db.query(AlphaSignal).filter_by(is_active=True).all()

    if not alphas:
        st.info("No active alphas in the registry to stress-test.")
    else:
        col1, col2 = st.columns([1, 2])

        with col1:
            st.markdown("### Select scenario")
            scenario_key = st.radio(
                "Scenario",
                list(SCENARIOS.keys()),
                format_func=lambda k: SCENARIOS[k]["name"],
                key="lab_scenario"
            )

            scenario = SCENARIOS[scenario_key]
            st.divider()
            st.caption(scenario["description"])
            st.caption(f"Historical analogs: {', '.join(scenario['historical_analogs'])}")
            st.caption(f"VIX spike: +{scenario['vix_spike']} pts | Duration: {scenario['duration_days']}d")

        with col2:
            st.markdown("### Alpha impact analysis")

            if st.button("Run stress test", type="primary", key="lab_run"):
                with st.spinner(f"Running {scenario['name']} across {len(alphas)} alpha(s)..."):
                    results = []
                    for alpha in alphas:
                        hyp = db.query(Hypothesis).filter_by(id=alpha.hypothesis_id).first()
                        if hyp:
                            impact = estimate_alpha_scenario_impact(alpha, hyp, scenario)
                            explanation = explain_scenario_impact(
                                alpha, hyp, scenario_key, impact
                            )
                            results.append({
                                "alpha": alpha,
                                "hyp": hyp,
                                "impact": impact,
                                "explanation": explanation
                            })
                    st.session_state["lab_results"] = results

            if "lab_results" in st.session_state:
                for r in st.session_state["lab_results"]:
                    with st.container(border=True):
                        impact = r["impact"]
                        alpha = r["alpha"]
                        hyp = r["hyp"]

                        h1, h2, h3, h4 = st.columns(4)
                        h1.markdown(f"**H#{hyp.hypothesis_number}**")
                        impact_pct = impact['estimated_portfolio_impact'] * 100
                        h2.metric(
                            "Est. Impact",
                            f"{impact_pct:.1f}%",
                            delta=f"{impact_pct:.1f}%",
                            delta_color="inverse"
                        )
                        h3.metric(
                            "Circuit Breaker",
                            "FIRES ✅" if impact["circuit_breaker_fires"] else "idle ⚠️"
                        )
                        h4.metric("Crowding", f"{impact['crowding_amplifier']:.2f}x")

                        st.caption(alpha.signal_name)
                        st.write(r["explanation"])

                        with st.expander("Impact breakdown"):
                            b1, b2, b3 = st.columns(3)
                            b1.metric("Sector contribution", f"{impact['sector_contribution']*100:.1f}%")
                            b2.metric("Factor contribution", f"{impact['factor_contribution']*100:.1f}%")
                            b3.metric("VIX spike", f"+{impact['vix_spike']} pts")
                            if impact["circuit_breaker_note"]:
                                st.caption(f"🔔 {impact['circuit_breaker_note']}")
                            if impact["idiosyncratic_note"]:
                                st.caption(f"⚡ {impact['idiosyncratic_note']}")

db.close()