import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

import streamlit as st
import pandas as pd
import json
from src.core.database import SessionLocal
from src.models.hypothesis import Hypothesis
from src.models.governance import GovernanceRecord
from src.models.research_memory import ResearchMemory
from src.models.alpha_registry import AlphaSignal
from sqlalchemy import text

st.set_page_config(page_title="AURUM V2 — Research Terminal", layout="wide")

def get_db():
    return SessionLocal()

def load_hypotheses(db):
    rows = db.query(Hypothesis).order_by(Hypothesis.hypothesis_number).all()
    data = []
    for h in rows:
        gov = db.query(GovernanceRecord).filter_by(hypothesis_id=h.id).first()
        data.append({
            "#": h.hypothesis_number,
            "Title": h.title,
            "Status": h.status.value if h.status else None,
            "Stage": gov.current_stage.value if gov else None,
            "Sharpe": h.sharpe_ratio,
            "Sortino": h.sortino_ratio,
            "Max DD": h.max_drawdown,
            "Ann. Return": h.annualized_return,
            "Win Rate": h.win_rate,
            "Holding (d)": h.expected_holding_days,
            "Has Debate": bool(gov and gov.debate_record),
        })
    return pd.DataFrame(data)

def load_memories(db):
    rows = db.query(ResearchMemory).order_by(ResearchMemory.created_at).all()
    return rows

# ── Sidebar navigation ────────────────────────────────────────────
st.sidebar.title("AURUM V2")
st.sidebar.caption("AI-native quantitative research firm")
page = st.sidebar.radio("Navigate", ["Research Feed", "Hypothesis Detail", "Research Memory", "Memory Lineage", "Alpha Registry"])

db = get_db()

# ── Page: Research Feed ───────────────────────────────────────────
if page == "Research Feed":
    st.title("Research feed")
    st.caption("Every hypothesis generated by the Research Scientist, with current governance stage and validated performance.")

    df = load_hypotheses(db)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total hypotheses", len(df))
    col2.metric("In paper trading", (df["Stage"] == "paper_trading").sum())
    col3.metric("Debated", df["Has Debate"].sum())
    col4.metric("Avg Sharpe (validated)", round(df["Sharpe"].dropna().mean(), 2) if df["Sharpe"].notna().any() else "—")

    st.divider()

    display_df = df.drop(columns=["Has Debate"]).copy()
    for col in ["Sharpe", "Sortino", "Max DD", "Ann. Return", "Win Rate"]:
        display_df[col] = display_df[col].apply(lambda x: f"{x:.3f}" if pd.notna(x) else "—")

    st.dataframe(display_df, use_container_width=True, hide_index=True)

# ── Page: Hypothesis Detail ───────────────────────────────────────
elif page == "Hypothesis Detail":
    st.title("Hypothesis detail")

    df = load_hypotheses(db)
    hyp_number = st.selectbox("Select hypothesis", df["#"].tolist())

    hyp = db.query(Hypothesis).filter_by(hypothesis_number=hyp_number).first()
    gov = db.query(GovernanceRecord).filter_by(hypothesis_id=hyp.id).first()

    st.subheader(f"#{hyp.hypothesis_number} — {hyp.title}")
    st.write(hyp.thesis)

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Sharpe", f"{hyp.sharpe_ratio:.3f}" if hyp.sharpe_ratio else "—")
    c2.metric("Sortino", f"{hyp.sortino_ratio:.3f}" if hyp.sortino_ratio else "—")
    c3.metric("Max DD", f"{hyp.max_drawdown:.1%}" if hyp.max_drawdown else "—")
    c4.metric("Ann. Return", f"{hyp.annualized_return:.1%}" if hyp.annualized_return else "—")
    c5.metric("Win Rate", f"{hyp.win_rate:.1%}" if hyp.win_rate else "—")

    st.divider()

    tab1, tab2, tab3, tab4 = st.tabs(["Signal components", "Governance timeline", "Committee debate", "Raw JSON"])

    with tab1:
        st.json(hyp.signal_components)
        st.caption(f"Conditions: {json.dumps(hyp.conditions)}")
        st.caption(f"Universe: {hyp.universe} | Holding period: {hyp.expected_holding_days} days")

    with tab2:
        if gov and gov.stage_history:
            for entry in gov.stage_history:
                with st.container(border=True):
                    st.markdown(f"**{entry.get('to_stage', 'unknown')}** — {entry.get('timestamp', '')[:19]}")
                    st.caption(entry.get("notes", ""))
        else:
            st.info("No governance history available.")

    with tab3:
        if gov and gov.debate_record:
            d = gov.debate_record
            colA, colB = st.columns(2)

            with colA:
                st.markdown("### 🐂 Bull case")
                for p in d["bull"]["thesis_points"]:
                    st.markdown(f"- {p}")
                st.success(f"**Strongest argument:** {d['bull']['strongest_argument']}")
                st.caption(f"Confidence: {d['bull']['confidence']}")

            with colB:
                st.markdown("### 🐻 Bear case")
                for p in d["bear"]["rebuttal_points"]:
                    st.markdown(f"- {p}")
                st.error(f"**Strongest objection:** {d['bear']['strongest_objection']}")
                st.caption(f"Confidence: {d['bear']['confidence']}")

            st.divider()
            st.markdown("### ⚖️ Risk assessment")
            for f in d["risk"]["risk_flags"]:
                st.markdown(f"- {f}")
            r1, r2, r3 = st.columns(3)
            r1.metric("Concentration risk", d["risk"]["concentration_risk"])
            r2.metric("Overall rating", d["risk"]["overall_risk_rating"])
            r3.metric("Position limit", d["risk"]["recommended_position_limit"][:30])

            st.divider()
            st.markdown("### 🏛️ Committee decision")
            j = d["judge"]
            decision_color = {"approve_paper_trading": "success", "reject": "error", "request_revision": "warning"}
            getattr(st, decision_color.get(j["decision"], "info"))(f"**{j['decision'].upper()}**")
            st.write(j["justification"])
            st.caption(f"Addressed bear objection: {j['addressed_bear_objection']}")
            if j.get("conditions_for_approval"):
                st.markdown("**Conditions:**")
                for c in j["conditions_for_approval"]:
                    st.markdown(f"- {c}")
        else:
            st.info("This hypothesis has not been through committee debate yet.")

    with tab4:
        st.json({
            "hypothesis": hyp.signal_components,
            "governance_stage": gov.current_stage.value if gov else None,
            "committee_decision": gov.committee_decision if gov else None,
        })

# ── Page: Research Memory ─────────────────────────────────────────
elif page == "Research Memory":
    st.title("Research memory")
    st.caption("Lessons extracted from failed or flawed research, consulted automatically before new hypothesis generation.")

    memories = load_memories(db)

    if not memories:
        st.info("No research memories yet.")
    else:
        st.metric("Total memories", len(memories))
        st.divider()

        for m in memories:
            with st.container(border=True):
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.markdown(f"**{m.failure_mode}**")
                    st.caption(f"From Hypothesis #{m.source_hypothesis_number} · {m.created_by}")
                with col2:
                    st.caption(f"Affects: {', '.join(m.affected_signal_types)}")

                st.write(m.lesson)

                with st.expander("Structured constraint"):
                    st.json(m.structured_constraint)

# ── Page: Memory Lineage ──────────────────────────────────────────
elif page == "Memory Lineage":
    st.title("Memory lineage")
    st.caption("The self-correcting research loop: a debate finds a flaw, a memory captures it, a future hypothesis adapts to it.")

    memories = load_memories(db)
    hyp_lookup = {h.hypothesis_number: h for h in db.query(Hypothesis).all()}

    if not memories:
        st.info("No memories yet.")
    else:
        for m in memories:
            source_hyp = hyp_lookup.get(m.source_hypothesis_number)
            influenced = m.influenced_hypothesis_numbers or []

            with st.container(border=True):
                col1, col2, col3 = st.columns([1, 1, 1])

                with col1:
                    st.markdown("**Source hypothesis**")
                    if source_hyp:
                        st.markdown(f"#{source_hyp.hypothesis_number} — {source_hyp.title}")
                        st.caption(f"Sharpe: {source_hyp.sharpe_ratio} · Max DD: {source_hyp.max_drawdown}")
                    else:
                        st.caption("Unknown source")

                with col2:
                    st.markdown("**→ Memory extracted →**")
                    st.markdown(f"`{m.failure_mode}`")
                    st.caption(m.lesson[:140] + "..." if len(m.lesson) > 140 else m.lesson)

                with col3:
                    st.markdown("**→ Influenced**")
                    if influenced:
                        for hyp_num in influenced:
                            target_hyp = hyp_lookup.get(hyp_num)
                            if target_hyp:
                                st.markdown(f"#{target_hyp.hypothesis_number} — {target_hyp.title}")
                                st.caption(f"Sharpe: {target_hyp.sharpe_ratio} · Max DD: {target_hyp.max_drawdown}")
                    else:
                        st.caption("Not yet applied to a new hypothesis")

        st.divider()
        st.markdown("### Full lineage chain")

        chain_md = """
H3 (no stat review, VIX gate flaw)
H4 (VIX gate flaw, selection bias)
        |
        v
   Memory: timing_mismatch
   Memory: selection_bias
        |
        v
H7 (10-day hold, fixed VIX=18 circuit breaker)
        |
        v
   Backtest reveals: 69.5% trigger rate, Sharpe 1.14 -> 0.31 with breaker on
        |
        v
   Memory: circuit_breaker_overcalibration
        |
        v
H8 (percentile-based dynamic threshold, 88th percentile VIX)
        |
        v
   Debate catches: circular calibration, no out-of-sample validation yet
        |
        v
   Paper trading mandated to validate before live deployment
"""
        st.code(chain_md, language=None)

        st.markdown("""
**The pattern**: every hypothesis after #4 exists because a debate or backtest found a specific,
named flaw in its predecessor. The system is not just generating ideas — it is generating ideas
that respond to its own documented failures, with the response itself then subjected to fresh
scrutiny by the committee.
""")

# ── Page: Alpha Registry ──────────────────────────────────────────
elif page == "Alpha Registry":
    st.title("Alpha registry")
    st.caption("Hypotheses that survived backtest, statistical validation, and committee debate — the system's actual research output.")

    alphas = db.query(AlphaSignal).order_by(AlphaSignal.registered_at).all()
    hyp_lookup = {h.id: h for h in db.query(Hypothesis).all()}

    if not alphas:
        st.info("No alphas registered yet.")
    else:
        c1, c2, c3 = st.columns(3)
        c1.metric("Registered alphas", len(alphas))
        c2.metric("Avg Sharpe", round(sum(a.sharpe_ratio for a in alphas) / len(alphas), 3))
        c3.metric("Active", sum(1 for a in alphas if a.is_active))

        st.divider()

        for a in alphas:
            hyp = hyp_lookup.get(a.hypothesis_id)
            with st.container(border=True):
                col1, col2 = st.columns([2, 1])

                with col1:
                    st.markdown(f"### {a.signal_name}")
                    if hyp:
                        st.caption(f"From Hypothesis #{hyp.hypothesis_number} · Universe: {a.universe} · "
                                   f"Registered {a.registered_at.strftime('%Y-%m-%d')}")

                with col2:
                    status = "🟢 Active" if a.is_active else "⚪ Inactive"
                    st.markdown(f"**{status}**")
                    if a.decay_flag:
                        st.warning("Decay flagged")
                    if a.retirement_recommended:
                        st.error("Retirement recommended")

                m1, m2, m3, m4, m5 = st.columns(5)
                m1.metric("Sharpe", f"{a.sharpe_ratio:.3f}")
                m2.metric("Sortino", f"{a.sortino_ratio:.3f}")
                m3.metric("Calmar", f"{a.calmar_ratio:.3f}")
                m4.metric("Max DD", f"{a.max_drawdown:.1%}")
                m5.metric("Win Rate", f"{a.win_rate:.1%}")

                if a.paper_trading_sharpe is not None:
                    st.caption(f"Paper trading Sharpe: {a.paper_trading_sharpe} "
                               f"(vs. backtest {a.sharpe_ratio})")

                with st.expander("Signal construction logic"):
                    st.code(a.signal_code, language="python")

                with st.expander("Features used"):
                    st.write(", ".join(a.features_used))

                # Latest learning report for this alpha
                latest = db.execute(text(
                    "SELECT paper_sharpe, paper_max_drawdown, paper_win_rate, "
                    "sharpe_degradation, vix_max_observed, vix_breach_occurred, "
                    "circuit_breaker_triggers, recommended_action, evaluated_at "
                    "FROM learning_reports WHERE hypothesis_id = :hid "
                    "ORDER BY evaluated_at DESC LIMIT 1"
                ), {"hid": str(a.hypothesis_id)}).fetchone()

                if latest:
                    with st.expander("Latest learning report"):
                        lr1, lr2, lr3 = st.columns(3)
                        lr1.metric("Paper Sharpe", f"{latest.paper_sharpe:.3f}",
                                   delta=f"{(latest.paper_sharpe - a.sharpe_ratio):.3f} vs backtest")
                        lr2.metric("Paper Max DD", f"{latest.paper_max_drawdown:.1%}")
                        lr3.metric("Recommendation", latest.recommended_action)
                        st.caption(f"Evaluated: {str(latest.evaluated_at)[:19]} | "
                                   f"VIX max: {latest.vix_max_observed} "
                                   f"({'breach' if latest.vix_breach_occurred else 'no breach'}) | "
                                   f"Circuit breaker fired: {latest.circuit_breaker_triggers}x")

db.close()